language: python
python:
  - "2.6"
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - pip install -r requirements.txt
  - pip install flake8
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi
script:
  - sh travis-build
language: python
