language: python
python:
  - "2.7"
  - "2.7_with_system_site_packages"
  - "3.6"
before_install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - sh travis-build
language: python
