language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env: USER_AGENT=Travis

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse; fi
  - pip install -r requirements.txt --use-mirrors
  - pip install -r dev_requirements.txt --use-mirrors
  - sudo apt-get update -qq

install: python yaclifw/main.py -h

script:
    - nosetests -v -d test
    - flake8 yaclifw test
